#subscriber
sub_assigned_virtual_position_topic: /uav1/teaming_planner/assigned_virtual_position

#publisher
pub_to_sense_avoid_topic: /uav1/sense_avoid/input_position

source_frame: /odom
target_frame: /uav1/t265_odom_frame

setpoint_z: 2.0

rate: 15
