/uav1/borealis_teaming_planner/sourceSegmentId: 1
/uav1/borealis_teaming_planner/modulePeriod: 0.025
/uav1/borealis_teaming_planner/numOfAgents: 2
/uav1/borealis_teaming_planner/intervalDistance: 0.5
/uav1/borealis_teaming_planner/planningHorizon: 25
/uav1/borealis_teaming_planner/debugVerbose: false
/uav1/borealis_teaming_planner/desiredHeight: 1.2
/uav1/borealis_teaming_planner/method: 1
