/uav2/borealis_teaming_planner/sourceSegmentId: 2
/uav2/borealis_teaming_planner/modulePeriod: 0.025
/uav2/borealis_teaming_planner/numOfAgents: 2
/uav2/borealis_teaming_planner/intervalDistance: 0.5
/uav2/borealis_teaming_planner/planningHorizon: 25
/uav2/borealis_teaming_planner/debugVerbose: false
/uav2/borealis_teaming_planner/desiredHeight: 1.2
/uav2/borealis_teaming_planner/useUWB: true
