/uav1/teaming_planner/sourceSegmentId: 0
/uav1/teaming_planner/modulePeriod: 0.025
/uav1/teaming_planner/numOfAgents: 3
/uav1/teaming_planner/intervalDistance: 0.5
/uav1/teaming_planner/planningHorizon: 25
/uav1/teaming_planner/debugVerbose: false

/uav2/teaming_planner/sourceSegmentId: 1
/uav2/teaming_planner/modulePeriod: 0.025
/uav2/teaming_planner/numOfAgents: 3
/uav2/teaming_planner/intervalDistance: 0.5
/uav2/teaming_planner/planningHorizon: 25
/uav2/teaming_planner/debugVerbose: false

/uav3/teaming_planner/sourceSegmentId: 2
/uav3/teaming_planner/modulePeriod: 0.025
/uav3/teaming_planner/numOfAgents: 3
/uav3/teaming_planner/intervalDistance: 0.5
/uav3/teaming_planner/planningHorizon: 25
/uav3/teaming_planner/debugVerbose: false
