/iris0/teaming_planner/sourceSegmentId: 0
/iris0/teaming_planner/modulePeriod: 0.025
/iris0/teaming_planner/numOfAgents: 1
/iris0/teaming_planner/intervalDistance: 0.5
/iris0/teaming_planner/planningHorizon: 25
/iris0/teaming_planner/debugVerbose: false