/uav1/borealis_hri_header_tf/headerFrameId: "uav1/t265_pose_frame"
/uav1/borealis_hri_header_tf/sourceSegmentId: 1
/uav1/borealis_hri_header_tf/pseudoChildFrameId: "uav1/pseudo_uwb_t265_frame"
/uav1/borealis_hri_header_tf/frameIdToCompare: "uav1"

