#subscriber
sub_desired_setpoint_topic: /desired_setpoint_position
sub_current_position_topic: /mavros/local_position/pose

#publisher
pub_setpoint_position_topic: /mavros/setpoint_position/local

setpoint_z: 2.0

rate: 30