#subscriber
sub_desired_setpoint_topic: /uav2/teaming_planner/assigned_virtual_position
sub_current_position_topic: /uav2/mavros/local_position/pose

#publisher
pub_setpoint_position_topic: /uav2/mavros/setpoint_position/local

setpoint_z: 2.0

rate: 15
